ecommerce_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: evocative-depot-427007-m8
      dataset: online_ecommerce_star_schema
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      # This replaces the literal '\n' text strings with real code linebreaks
      keyfile_json: "{{ env_var('DBT_ENV_SECRET_BQ_CREDENTIALS') | replace('\\n', '\n') }}"