ecommerce_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: evocative-depot-427007-m8
      dataset: online_ecommerce_star_schema
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      # Uses the environment variable if present (CI/CD), otherwise uses your local path
      keyfile: "{{ env_var('DBT_GCP_JSON_KEY_FILE_LOCATION', 'C:\\Users\\shane\\.dbt\\sa_key_file.json') }}"