name: dbt_ci_cd

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

env:
  DBT_PROJECT_DIR: ./
  DBT_PROFILES_DIR: ./

jobs:
  dbt_ci_cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.x'

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core==1.7.18 dbt-bigquery==1.7.9

    - name: Run dbt pipeline
      env:
        BASE64_GCP_KEY: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
      run: |
        # Using printf ensures the Base64 string is decoded accurately with zero trailing noise
        printf "%s" "$BASE64_GCP_KEY" | base64 --decode > ./gcp_key.json
        
        dbt debug --target ci
        dbt deps
        dbt seed --target ci
        dbt run --target ci

    - name: Test dbt models
      env:
        DBT_GCP_JSON_KEY_FILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
      run: |
        dbt test --target ci